services:
  knowledge-api:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.prod
    image: knowledge-api-prod:latest
    container_name: knowledge-api-prod
    ports:
      - "8000:8000"
    environment:
      - AZURE_SQL_SERVER=${AZURE_SQL_SERVER}
      - AZURE_SQL_DATABASE=${AZURE_SQL_DATABASE}
      - AZURE_SQL_USER=${AZURE_SQL_USER}
      - AZURE_SQL_PASSWORD=${AZURE_SQL_PASSWORD}
      - AZURE_SEARCH_ENDPOINT=${AZURE_SEARCH_ENDPOINT}
      - AZURE_SEARCH_KEY=${AZURE_SEARCH_KEY}
      - AZURE_SEARCH_INDEX_NAME=${AZURE_SEARCH_INDEX_NAME}
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G