services:
  knowledge-api:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: knowledge-api-dev:latest
    container_name: knowledge-api-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - AZURE_SQL_SERVER=${AZURE_SQL_SERVER}
      - AZURE_SQL_DATABASE=${AZURE_SQL_DATABASE}
      - AZURE_SQL_USER=${AZURE_SQL_USER}
      - AZURE_SQL_PASSWORD=${AZURE_SQL_PASSWORD}
      - AZURE_SEARCH_ENDPOINT=${AZURE_SEARCH_ENDPOINT}
      - AZURE_SEARCH_KEY=${AZURE_SEARCH_KEY}
      - AZURE_SEARCH_INDEX_NAME=${AZURE_SEARCH_INDEX_NAME}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-config /app/config/logging_config.yml