services:
  knowledge-api:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: knowledge-api-dev:latest
    container_name: knowledge-api-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-config /app/config/logging_config.yml