"""add is_active column to documents table

Revision ID: 3c777ad8ef0c
Revises: f3dabb3f5bd7
Create Date: 2025-04-27 08:57:34.454841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '3c777ad8ef0c'
down_revision: Union[str, None] = 'f3dabb3f5bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add is_active column to documents table
    op.add_column('documents', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true(), comment="有効フラグ（UIでOn/Off切り替え可能）"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SessionManagement',
    sa.Column('ChannelID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('BOT_ID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('SessionID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Timestamp', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ChannelID', 'BOT_ID', name='PK__SessionM__41FDC3A78E9B7F91')
    )
    op.create_table('Organizations',
    sa.Column('ORGANIZATION_ID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('ORGANIZATION_NAME', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ORGANIZATION_IS_ACTIVE', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('VALID_FROM', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('VALID_TO', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('PROMPT_UPDATE', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('ALLOWED_PRODUCT_TYPES', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ALLOWED_MODEL_TYPES', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ALLOWED_PROC_TYPES', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ALLOWED_PRODUCT_NAMES', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ALLOWED_MAX_DIALOGUE_TURNS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ALLOWED_MAX_DIALOGUE_CHARS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ALLOWED_OCR', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ALLOWED_OCR_FORMING', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ORGANIZATION_ID', name='PK__Organiza__4871EE3C746DF7BE')
    )
    op.create_table('Users',
    sa.Column('USER_ID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('USER_ID_SLACK', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('USER_ID_TEAMS', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('USER_ID_GOOGLECHAT', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('USER_NAME', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('EMAIL', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ORGANIZATION_ID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('USER_IS_ACTIVE', mssql.BIT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('USER_ID', name='PK__Users__F3BEEBFF9E6CB6F4')
    )
    op.create_table('ChatLogs',
    sa.Column('ID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Actor', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Timestamp', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('MessageText', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SpeakerID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MemberName', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ChannelID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ChannelName', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Context', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('RESPONSE_MODEL', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('INPUT_TOKENS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('OUTPUT_TOKENS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TOTAL_TOKENS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('EventID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SessionID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('BOT_ID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('USER_ID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='PK__ChatLogs__3214EC27B4E062ED')
    )
    op.create_table('MonthlyUsage',
    sa.Column('SUBSCRIPTION_ID', mssql.UNIQUEIDENTIFIER(), server_default=sa.text('(newid())'), autoincrement=False, nullable=False),
    sa.Column('ORGANIZATION_ID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('YEAR_MONTH', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('USAGE_LIMIT', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('USAGE_COUNT', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('SUBSCRIPTION_ID', name='PK__MonthlyU__1869FC7A9AE636E5')
    )
    op.create_table('ProcessedEvents',
    sa.Column('EventID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Status', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('UnknownLogs',
    sa.Column('ID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('UnknownType', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Timestamp', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('BotID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('UserID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('UserName', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('UserID2', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ChannelID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MessageText', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='PK__UnknownL__3214EC277E01D155')
    )
    op.create_table('ProcTime',
    sa.Column('EventID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Process', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Timestamp', sa.DATETIME(), autoincrement=False, nullable=True)
    )
    op.create_table('documents',
    sa.Column('id', sa.VARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.VARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('meta_data', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='FK__documents__datas__08B54D69', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK__document__3213E83FA73D6332')
    )
    op.create_table('Config',
    sa.Column('BOT_ID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('BOT_NAME', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SLACK_BOT_TOKEN', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('BOT_PW', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('TENANT_ID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('TEAM_ID', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('GPT_SYSTEM_PROMPT', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('GPT_SYSTEM_PROMPT_2', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('GPT_SYSTEM_PROMPT_3', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('GPT_SYSTEM_PROMPT_4', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('GPT_SYSTEM_PROMPT_5', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('GPT_SYSTEM_PROMPT_6', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('GPT_SYSTEM_PROMPT_7', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('GPT_SYSTEM_PROMPT_OCR_FORMING', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('GPT_SYSTEM_PROMPT_VISION', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MAX_DIALOGUE_TURNS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MAX_DIALOGUE_CHARS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MAX_CONTEXT_REFS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MAX_CONTEXT_CHARS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MAX_TOKENS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRODUCT_TYPE', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('MODEL_TYPE', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PROC_TYPE', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PRODUCT_NAME', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('IMAGE_UNDERSTANDING', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('OCR', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('OCR_FORMING', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SERVICE_ACCOUNT_FILE', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SERVICE_ACCOUNT_FILEPATH', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('BOT_IS_ACTIVE', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('HOW_TO_USE', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('EVAL_CHARS_LIMIT', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('EVAL_SYSTEM_PROMPT', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('FB_REPORT_SYSTEM_PROMPT', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('DebugLogs',
    sa.Column('Timestamp', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('memo', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True)
    )
    op.create_table('datasets',
    sa.Column('id', sa.VARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('meta_data', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('is_active', mssql.BIT(), server_default=sa.text('((1))'), autoincrement=False, nullable=False, comment='有効フラグ（UIでOn/Off切り替え可能）'),
    sa.PrimaryKeyConstraint('id', name='PK__datasets__3213E83FABDCEC49')
    )
    # ### end Alembic commands ###
